### ISSUE TITLE
Read configuration from file

### ISSUE THREAD

**Issue by petemounce** [martinlindhe/wmi_exporter#233]
Would it be reasonable to extend this excellent app to let it read configuration from a file? I'm setting it up for the first time, running it via NSSM, and finding that the service declaration with various flags and per-process filters is quite long. My own is:

```shell
"C:\wmi_exporter\wmi_exporter.exe" --log.format logger:eventlog?name=wmi_exporter  --telemetry.addr :5000 --collectors.enabled "cpu,cs,logical_disk,net,os,service,system,textfile" --collector.service.services-where "Name='buildkite-agent'" --collector.service.services-where "Name='wmi_exporter'"
```

I was thinking along the lines of TOML via https://github.com/toml-lang/toml

```toml
listen_address = 9182

[log]
format = "eventlog"
name = "wmi_exporter" 

[collectors_enabled]

  [collectors_enabled.cpu]
  [collectors_enabled.cs]
  [collectors_enabled.logical_disk]
  [collectors_enabled.net]
  [collectors_enabled.os]
  [collectors_enabled.services]
    filters = [
      "Name='wmi_exporter'",
      "Name='something_else'",
    ]
  [collectors_enabled.process]
    filters = [
      "Name='firefox%'",
      "Name='something_else%'",
    ]
  [collectors_enabled.service]
  [collectors_enabled.system]
  [collectors_enabled.textfile]
    directory = "c:/wmi_exporter/metrics_files"
```
