### ISSUE TITLE
Service immediately stops: couldn't load collectors cpu & vmware

### ISSUE THREAD

**Issue by AirCombat** [martinlindhe/wmi_exporter#366]
v0.7.0, installed via MSI, Windows Server 2019 Core

`ENABLED_COLLECTORS=cpu,cs,dns,logical_disk,net,os,service,system,vmware`

Every time i start the service it stops immediately with the following events:

Event 102: Couldn't load collectors: collector 'vmware'' not available
Event 102: Couldn't load collectors: collector ''cpu' not available
Event 101: No where-clause specified for service collector. This will generate a very large number of metrics!

About 500 of 102 in the past few hours.
About 20 of 101 in the past few hours.

Please let me know if theres any way to get more details info.

The only thing that is configured differently from vanilla on this server is disabled old TLS versions and ciphers and enabling fips mode.

Is there a way of changing the config after install?

I can survive without vmware but cpu is important.

**Comment by AirCombat** [comment]
I have reinstalled with: cs,dns,logical_disk,net,os,service,system and now get:
Couldn't load collectors: collector 'system'' not available

**Comment by carlpett** [comment]
Hm, this is very odd. Is it consistently just the first and last ones in your list that do not work?
Grasping at straws here, but are you by any chance using a non-english keyboard? Your copied error messages have mismatches in the quote-marks, and I know some locales use quotes that are not the ascii " and '.

**Comment by AirCombat** [comment]
en_GB :)
Its only showing system since i reinstalled it without vmware and cpu.

I can confirm the quotes are coming from the application like that:
https://imgur.com/BjDc7Ar

(Viewing from Windows Admin Centre as its Windows Core)

**Comment by AirCombat** [comment]
`PS C:\Users\Administrator.ONLINE> Get-EventLog -LogName Application -Newest 9 | ft -AutoSize

Index Time         EntryType Source       InstanceID Message
----- ----         --------- ------       ---------- -------
 7876 Jul 21 20:03 Error     wmi_exporter        102 Couldn't load collectors: collector 'system'' not available
 7875 Jul 21 20:03 Warning   wmi_exporter        101 No where-clause specified for service collector. This will generate a very la...
 7874 Jul 21 20:03 Error     wmi_exporter        102 Couldn't load collectors: collector 'system'' not available
 7873 Jul 21 20:03 Warning   wmi_exporter        101 No where-clause specified for service collector. This will generate a very la...
 7872 Jul 21 20:03 Error     wmi_exporter        102 Couldn't load collectors: collector 'system'' not available
 7871 Jul 21 20:03 Warning   wmi_exporter        101 No where-clause specified for service collector. This will generate a very la...
 7870 Jul 21 20:03 Error     wmi_exporter        102 Couldn't load collectors: collector 'system'' not available
 7869 Jul 21 20:03 Warning   wmi_exporter        101 No where-clause specified for service collector. This will generate a very la...
 7868 Jul 21 20:03 Error     wmi_exporter        102 Couldn't load collectors: collector 'system'' not available`

**Comment by carlpett** [comment]
Drat :) 
Just to make certain the quoting is the issue, could you try installing or running the exporter without any arguments?

**Comment by AirCombat** [comment]
My mistake

I changed this:
```
- name: Install prometheus WMI exporter
  win_package:
    path: D:\ansible\installers\wmi_exporter-0.7.0-amd64.msi
    log_path: D:\ansible\installers\wmi_exporter-0.7.0-amd64.log
    arguments: ENABLED_COLLECTORS="{{prometheus_collectors}}"
    state: present

```
to this:

```
- name: Install prometheus WMI exporter
  win_package:
    path: D:\ansible\installers\wmi_exporter-0.7.0-amd64.msi
    log_path: D:\ansible\installers\wmi_exporter-0.7.0-amd64.log
    arguments: "{{ 'ENABLED_COLLECTORS=' + prometheus_collectors }}"
    state: present
```

`prometheus_collectors: ad,cpu,cs,dns,logical_disk,net,os,service,system,vmware`

I believe it was adding double quotes around the ENABLED_COLLECTORS argument. I appreciate your switch weekend response.
